In [3]:
import numpy as np

In [1]:
[
    ["Yonah", "Dallas", "Hyacinth"],
    ["Yonah", "Dallas", "Hyacinth"], 
    []
]

In [4]:
lst = [1,2,3,4,5]

In [5]:
lst

[1, 2, 3, 4, 5]

In [6]:
lst_np = np.array(lst)

In [9]:
lst_np

array([1, 2, 3, 4, 5])

In [10]:
twod_lst = [
    [1,2,3],
    [4,5,6]
]

In [13]:
twod_lst_np = np.array(twod_lst)
twod_lst_np

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
twod_lst_np.shape

(2, 3)

In [15]:
lst_np.shape

(5,)

In [18]:
twod_lst_np.reshape((-1,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
lst_np

array([1, 2, 3, 4, 5])

In [23]:
twod_lst_np

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#twod_lst_np[0,0] == twod_lst_np[0][0]

1

In [28]:
twod_lst_np[:, 0]

array([1, 4])

In [30]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
matrix = np.arange(100).reshape((20, 5))
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [63]:
matrix2 = np.arange(1, 200, 2).reshape((20, 5))
matrix2

array([[  1,   3,   5,   7,   9],
       [ 11,  13,  15,  17,  19],
       [ 21,  23,  25,  27,  29],
       [ 31,  33,  35,  37,  39],
       [ 41,  43,  45,  47,  49],
       [ 51,  53,  55,  57,  59],
       [ 61,  63,  65,  67,  69],
       [ 71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89],
       [ 91,  93,  95,  97,  99],
       [101, 103, 105, 107, 109],
       [111, 113, 115, 117, 119],
       [121, 123, 125, 127, 129],
       [131, 133, 135, 137, 139],
       [141, 143, 145, 147, 149],
       [151, 153, 155, 157, 159],
       [161, 163, 165, 167, 169],
       [171, 173, 175, 177, 179],
       [181, 183, 185, 187, 189],
       [191, 193, 195, 197, 199]])

In [68]:
matrix[:, 0] / matrix2[:,1]

array([0.        , 0.38461538, 0.43478261, 0.45454545, 0.46511628,
       0.47169811, 0.47619048, 0.47945205, 0.48192771, 0.48387097,
       0.48543689, 0.48672566, 0.48780488, 0.4887218 , 0.48951049,
       0.49019608, 0.49079755, 0.49132948, 0.49180328, 0.49222798])

In [72]:
np.dot(matrix, matrix2.reshape((5, 20)))

array([[ 1210,  1230,  1250,  1270,  1290,  1310,  1330,  1350,  1370,
         1390,  1410,  1430,  1450,  1470,  1490,  1510,  1530,  1550,
         1570,  1590],
       [ 3235,  3305,  3375,  3445,  3515,  3585,  3655,  3725,  3795,
         3865,  3935,  4005,  4075,  4145,  4215,  4285,  4355,  4425,
         4495,  4565],
       [ 5260,  5380,  5500,  5620,  5740,  5860,  5980,  6100,  6220,
         6340,  6460,  6580,  6700,  6820,  6940,  7060,  7180,  7300,
         7420,  7540],
       [ 7285,  7455,  7625,  7795,  7965,  8135,  8305,  8475,  8645,
         8815,  8985,  9155,  9325,  9495,  9665,  9835, 10005, 10175,
        10345, 10515],
       [ 9310,  9530,  9750,  9970, 10190, 10410, 10630, 10850, 11070,
        11290, 11510, 11730, 11950, 12170, 12390, 12610, 12830, 13050,
        13270, 13490],
       [11335, 11605, 11875, 12145, 12415, 12685, 12955, 13225, 13495,
        13765, 14035, 14305, 14575, 14845, 15115, 15385, 15655, 15925,
        16195, 16465],
       [13

In [73]:
None

In [44]:
lst_np

array([1, 2, 3, 4, 5])

In [47]:
lst_np.mean()

3.0

In [49]:
np.median(lst_np)

3.0

In [51]:
lst_np.max()

5

3.0

In [59]:
lst_np

array([1, 2, 3, 4, 5])

## Exercise  solution

In [74]:
def func(np_arr):
    print(np_arr.min())
    print(np.std(np_arr))
    print(np.prod(np_arr))
    print(np.dot(np_arr, np_arr))
    print(np_arr - 4)
    
    
    
    

In [75]:
arr = np.array([3,4,22,45,8])

In [76]:
func(arr)

3
15.83161394173064
95040
2598
[-1  0 18 41  4]
