In [7]:
import numpy as np
a = np.random.randint(1, 100, size=(5, 5))
a

array([[55, 63, 76, 74,  3],
       [29, 84, 60, 45, 12],
       [59, 97, 70, 43, 70],
       [35, 16, 37, 33,  6],
       [94, 69, 62, 57, 15]])

In [16]:
a[2]

array([ 59,  97,  70,  43, 156])

In [17]:
a[:, 2]

array([76, 60, 70, 37,  7])

In [18]:
a[-1] = 7
a

array([[ 55,  63,  76,  74, 118],
       [ 29,  84,  60,  45, 113],
       [ 59,  97,  70,  43, 156],
       [ 35,  16,  37,  33,  51],
       [  7,   7,   7,   7,   7]])

In [14]:
sum_columns = np.sum((a[0], a[1]), axis = 0)
a[:,-1]
a

array([[ 55,  63,  76,  74, 118],
       [ 29,  84,  60,  45, 113],
       [ 59,  97,  70,  43, 156],
       [ 35,  16,  37,  33,  51],
       [  7,   7,   7,   7,   7]])