In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
titanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
age = np.unique(titanic_df['Age'])
age

array([ 0.42,  0.67,  0.75,  0.83,  0.92,  1.  ,  2.  ,  3.  ,  4.  ,
        5.  ,  6.  ,  7.  ,  8.  ,  9.  , 10.  , 11.  , 12.  , 13.  ,
       14.  , 14.5 , 15.  , 16.  , 17.  , 18.  , 19.  , 20.  , 20.5 ,
       21.  , 22.  , 23.  , 23.5 , 24.  , 24.5 , 25.  , 26.  , 27.  ,
       28.  , 28.5 , 29.  , 30.  , 30.5 , 31.  , 32.  , 32.5 , 33.  ,
       34.  , 34.5 , 35.  , 36.  , 36.5 , 37.  , 38.  , 39.  , 40.  ,
       40.5 , 41.  , 42.  , 43.  , 44.  , 45.  , 45.5 , 46.  , 47.  ,
       48.  , 49.  , 50.  , 51.  , 52.  , 53.  , 54.  , 55.  , 55.5 ,
       56.  , 57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 63.  , 64.  ,
       65.  , 66.  , 70.  , 70.5 , 71.  , 74.  , 80.  ,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,

In [7]:
from sklearn.preprocessing import LabelEncoder
gle = LabelEncoder()
age_labels = gle.fit_transform(titanic_df['Age'])
age_mappings = {index: label for index, label in 
                  enumerate(gle.classes_)}
age_mappings

{0: 0.42,
 1: 0.67,
 2: 0.75,
 3: 0.83,
 4: 0.92,
 5: 1.0,
 6: 2.0,
 7: 3.0,
 8: 4.0,
 9: 5.0,
 10: 6.0,
 11: 7.0,
 12: 8.0,
 13: 9.0,
 14: 10.0,
 15: 11.0,
 16: 12.0,
 17: 13.0,
 18: 14.0,
 19: 14.5,
 20: 15.0,
 21: 16.0,
 22: 17.0,
 23: 18.0,
 24: 19.0,
 25: 20.0,
 26: 20.5,
 27: 21.0,
 28: 22.0,
 29: 23.0,
 30: 23.5,
 31: 24.0,
 32: 24.5,
 33: 25.0,
 34: 26.0,
 35: 27.0,
 36: 28.0,
 37: 28.5,
 38: 29.0,
 39: 30.0,
 40: 30.5,
 41: 31.0,
 42: 32.0,
 43: 32.5,
 44: 33.0,
 45: 34.0,
 46: 34.5,
 47: 35.0,
 48: 36.0,
 49: 36.5,
 50: 37.0,
 51: 38.0,
 52: 39.0,
 53: 40.0,
 54: 40.5,
 55: 41.0,
 56: 42.0,
 57: 43.0,
 58: 44.0,
 59: 45.0,
 60: 45.5,
 61: 46.0,
 62: 47.0,
 63: 48.0,
 64: 49.0,
 65: 50.0,
 66: 51.0,
 67: 52.0,
 68: 53.0,
 69: 54.0,
 70: 55.0,
 71: 55.5,
 72: 56.0,
 73: 57.0,
 74: 58.0,
 75: 59.0,
 76: 60.0,
 77: 61.0,
 78: 62.0,
 79: 63.0,
 80: 64.0,
 81: 65.0,
 82: 66.0,
 83: 70.0,
 84: 70.5,
 85: 71.0,
 86: 74.0,
 87: 80.0,
 88: nan,
 89: nan,
 90: nan,
 91: nan,
 92: nan,
 

In [10]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = StandardScaler()
scaler.fit_transform(titanic_df._get_numeric_data())[0:2]

array([[-1.73010796, -0.78927234,  0.82737724, -0.53037664,  0.43279337,
        -0.47367361, -0.50244517],
       [-1.72622007,  1.2669898 , -1.56610693,  0.57183099,  0.43279337,
        -0.47367361,  0.78684529]])

In [12]:
mm_scaler = MinMaxScaler()
mm_scaler.fit_transform(titanic_df._get_numeric_data())[0:2]

array([[0.        , 0.        , 1.        , 0.27117366, 0.125     ,
        0.        , 0.01415106],
       [0.0011236 , 1.        , 0.        , 0.4722292 , 0.125     ,
        0.        , 0.13913574]])