In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from numpy.linalg import norm #(a-b)

In [2]:
data = np.random.randint(0, 50, (10,3))
data

array([[30,  5,  9],
       [46, 41, 41],
       [25, 21, 28],
       [ 7, 46, 36],
       [ 3, 48, 23],
       [32, 38, 49],
       [ 3, 17, 25],
       [35, 22, 38],
       [ 0,  0, 33],
       [12, 36, 26]])

In [17]:
X_train

array([[46, 41],
       [ 3, 17],
       [30,  5],
       [35, 22],
       [ 0,  0],
       [32, 38],
       [25, 21],
       [12, 36]])

In [18]:
y_train

array([41, 25,  9, 38, 33, 49, 28, 26])

In [19]:
X_test

array([[ 3, 48],
       [ 7, 46]])

In [20]:
y_test

array([23, 36])

In [6]:
class KNNRegressor:
    
    def __init__(self, k):
        self.k = k
    
    def fit(self, X, y):
        self.X = X
        self.y = y
    
    def predict(self, X_test):
        #given (17,  1) loop thru 
        predictions = []
        for x_test in X_test:
            dist_list = []
            for data_point in self.X:
                dist = norm(x_test - data_point)
                dist_list.append(dist)
            indices = np.argpartition(dist_list, self.k)[:self.k]
            y_train_top = self.y[indices]
            final_prediction = y_train_top.mean()
            predictions.append(final_prediction)
        return predictions
            
    

In [7]:
np.argpartition([3,4,6,2,4.1], 3)[:3]

array([3, 0, 1])

In [8]:
np.array((17,  1)) - np.array((29,  2))

array([-12,  -1])

In [9]:
norm(np.array((17,  1)) - np.array((29,  2)))

12.041594578792296

In [10]:
X = data[:, :2]
y = data[:, -1]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [12]:
y_test

array([23, 36])

In [13]:
X_test

array([[ 3, 48],
       [ 7, 46]])

In [14]:
knn = KNNRegressor(k=3)

In [15]:
knn.fit(X, y)

In [16]:
knn.predict(X_test)

[28.333333333333332, 28.333333333333332]

In [21]:
knn.predict(X_train)

[42.666666666666664,
 28.0,
 25.0,
 38.333333333333336,
 22.333333333333332,
 42.666666666666664,
 25.0,
 28.333333333333332]

In [22]:
knn.predict(y_train)

[42.666666666666664,
 38.333333333333336,
 28.666666666666668,
 42.666666666666664,
 38.333333333333336,
 42.666666666666664,
 38.333333333333336,
 38.333333333333336]

In [23]:
knn.predict(y_test)

[30.666666666666668, 42.666666666666664]