In [2]:
#from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split
#import seaborn as sns

In [5]:
titanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv').dropna()
titanic_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [6]:
X = titanic_df._get_numeric_data().drop(columns="Survived")
y = titanic_df.Survived

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [10]:
X_train

PassengerId  Pclass   Age  SibSp  Parch     Fare
292          293       2  36.0      0      0  12.8750
512          513       1  36.0      0      0  26.2875
627          628       1  21.0      0      0  77.9583
496          497       1  54.0      1      0  78.2667
291          292       1  19.0      1      0  91.0792
..           ...     ...   ...    ...    ...      ...
887          888       1  19.0      0      0  30.0000
257          258       1  30.0      0      0  86.5000
174          175       1  56.0      0      0  30.6958
781          782       1  17.0      1      0  57.0000
193          194       2   3.0      1      1  26.0000

[137 rows x 6 columns]

In [19]:
hyperparameters = {'C':[0.0001, 0.001 , 0.01 , 0.1 , 1 , 10, 100],
                  "max_iter":[1000, 500, 100] }

In [20]:
log = LogisticRegression()

In [21]:
gs = GridSearchCV(log, hyperparameters, cv=5, n_jobs=-1,  scoring = 'accuracy')

In [22]:
gs.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100],
                         'max_iter': [1000, 500, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [23]:
gs.cv_results_

{'mean_fit_time': array([0.29405799, 0.02347379, 0.04087477, 0.06488719, 0.03746347,
        0.04128346, 0.07589159, 0.09985709, 0.10280805, 0.07264442,
        0.0734786 , 0.08620157, 0.10962906, 0.14392176, 0.12269921,
        0.06839695, 0.07323155, 0.05909262, 0.04218812, 0.04358897,
        0.04069734]),
 'std_fit_time': array([0.13553935, 0.00700155, 0.02450088, 0.02700606, 0.00681839,
        0.02504925, 0.02251899, 0.05933815, 0.08363368, 0.01688858,
        0.01686313, 0.04726182, 0.06995557, 0.05091126, 0.04119864,
        0.02700844, 0.02319422, 0.03339429, 0.01202817, 0.0252642 ,
        0.01497082]),
 'mean_score_time': array([0.00206342, 0.00305772, 0.00225468, 0.00186391, 0.00173311,
        0.00256224, 0.01640658, 0.02678847, 0.00210147, 0.00492654,
        0.00543895, 0.00263286, 0.00162215, 0.0017024 , 0.01170859,
        0.01367588, 0.00302396, 0.002807  , 0.0012814 , 0.00148149,
        0.00204263]),
 'std_score_time': array([0.00086249, 0.00183117, 0.00080211, 0.00

In [25]:
gs.cv_results_['mean_test_score']

array([0.7005291 , 0.7005291 , 0.7005291 , 0.68571429, 0.68571429,
       0.68571429, 0.69285714, 0.69285714, 0.69285714, 0.68571429,
       0.68571429, 0.68571429, 0.6494709 , 0.6494709 , 0.6494709 ,
       0.6494709 , 0.6494709 , 0.6494709 , 0.6494709 , 0.6494709 ,
       0.6494709 ])

In [26]:
gs.cv_results_['rank_test_score']

array([ 1,  1,  1,  7,  7,  7,  4,  4,  4,  7,  7,  7, 13, 13, 13, 13, 13,
       13, 13, 13, 13], dtype=int32)

In [24]:
gs.best_score_

0.7005291005291004

In [ ]:
gs.cv_results_['mean_test_score']
array([0.9279615 , 0.94027325, 0.94025772, 0.94904518, 0.95081509, 0.95081509, 0.95433939])

>>> gs.cv_results_['rank_test_score']
array([7, 5, 6, 4, 2, 2, 1], dtype=int32)

>>> clf.best_score_
0.954