In [1]:
import numpy as np
a = np.random.randint(1, 100, size=(5, 5))
print(a)

[[14 54 59 48 68]
 [42 64 30 53 36]
 [15 10  6 64 37]
 [40 17 54  5 20]
 [35 62 53 39 73]]


In [2]:
row = a[2]
print(row)

[15 10  6 64 37]


In [3]:
column = a[:, 2]
print(column)

[59 30  6 54 53]


In [4]:
a[4] = [7, 7, 7, 7, 7]
print(a)

[[14 54 59 48 68]
 [42 64 30 53 36]
 [15 10  6 64 37]
 [40 17 54  5 20]
 [ 7  7  7  7  7]]


In [5]:
a[:, 4] = a[:, 0] + a[:, 1]
print(a)

[[ 14  54  59  48  68]
 [ 42  64  30  53 106]
 [ 15  10   6  64  25]
 [ 40  17  54   5  57]
 [  7   7   7   7  14]]
